### ISSUE TITLE
Error: Cannot invoke a non-'const' constructor where a const expression is expected. Try using a constructor or factory that is 'const'.

### ISSUE THREAD

**Issue by tenSunFree** [pdliuw/flutter_app_sample#5]
Following is the error message
![2020-04-01_134518](https://user-images.githubusercontent.com/23090085/78103633-fb786100-741f-11ea-82ad-886db71d53e4.jpg)
![2020-04-01_134646](https://user-images.githubusercontent.com/23090085/78103639-fe735180-741f-11ea-83ca-ee33c8adb563.jpg)

My solution, delete BarChartGroupData const
![2020-04-01_135459](https://user-images.githubusercontent.com/23090085/78103818-6a55ba00-7420-11ea-91b9-0cc88b27486c.jpg)

**Comment by pdliuw** [comment]
> 以下是错误消息
> ![2020-04-01_134518](https://user-images.githubusercontent.com/23090085/78103633-fb786100-741f-11ea-82ad-886db71d53e4.jpg)
> ![2020-04-01_134646](https://user-images.githubusercontent.com/23090085/78103639-fe735180-741f-11ea-83ca-ee33c8adb563.jpg)
> 
> 我的解决方案，删除BarChartGroupData const
> ![2020-04-01_135459](https://user-images.githubusercontent.com/23090085/78103818-6a55ba00-7420-11ea-91b9-0cc88b27486c.jpg)

Thank you very much for the solution

**Comment by pdliuw** [comment]
This issue has been fixed
