### ISSUE TITLE
flushbar_route.dart:303:8: Error: The method 'FlushbarRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'

### ISSUE THREAD

**Issue by tenSunFree** [pdliuw/flutter_app_sample#6]
Following is the error message
![2020-04-01_143019](https://user-images.githubusercontent.com/23090085/78106244-932c7e00-7425-11ea-977a-1d3dc536c5c3.jpg)

My solution, remove the automatic update (^) of the flushbar
![2020-04-01_143316](https://user-images.githubusercontent.com/23090085/78106461-0635f480-7426-11ea-90d1-3918b7a61a86.jpg)

**Comment by pdliuw** [comment]
We will give a better solution as soon as possible

**Comment by pdliuw** [comment]
> 以下是错误消息
> ![2020-04-01_143019](https://user-images.githubusercontent.com/23090085/78106244-932c7e00-7425-11ea-977a-1d3dc536c5c3.jpg)
> 
> 我的解决方案，删除冲洗栏的自动更新（^）
> ![2020-04-01_143316](https://user-images.githubusercontent.com/23090085/78106461-0635f480-7426-11ea-90d1-3918b7a61a86.jpg)

This issue has been fixed
