### ISSUE TITLE
setState() or markNeedsBuild() called when widget tree was locked.

### ISSUE THREAD

**Issue by tenSunFree** [pdliuw/flutter_app_sample#7]
When the right Drawer is displayed, if the function of right side sliding is turned off, an error message will appear
![2020-04-02_232410](https://user-images.githubusercontent.com/23090085/78268628-08d63e00-753b-11ea-9bc5-36aebe3bcc39.jpg)

This is my current solution, maybe you have a better solution?
![2020-04-02_233657](https://user-images.githubusercontent.com/23090085/78268648-125fa600-753b-11ea-82bf-73f0efdc6567.jpg)

**Comment by pdliuw** [comment]
. We are sorry, after our careful investigation, we found that the solution you provided does not completely solve the above problem
2. After adopting your solution, we will go through: enter the homepage-> open the left side slide-> select to open the right side slide-> close the left side slide-> open the right side slide-> select close the right side slide-> open left Side slip-> Check to turn on the right side slide-> Turn off the left side slide-> Turn on the right side slide-> Check to turn off the right side slide-> The above problem is reproduced
3. We are happy to receive your feedback, indicating that you have paid some attention to this project, and we look forward to your continued to provide us with valuable comments and solutions
